name: Ricardo Kullock

description: Nova tentativa

baseurl: "/meusite"

markdown: kramdown

theme: jekyll-theme-midnight

timezone: America/Sao_Paulo

future: true

include:
 - _pages
 - _posts

permalink: /:title/

exclude:
 - Gemfile
 - Gemfile.lock
 - LICENSE
 - README.md
 - CNAME
